// Generated by https://quicktype.io

export interface InfoPagina {
    titulo?:    string;
    email?:     string;
    nombre?:    string;
    facebook?:  string;
    twitter?:   string;
    instagram?: string;
    tublr?:     string;
}
