// Generated by https://quicktype.io

export interface Productos {
    id_producto?:        number;
    fk_categoria?:       {
        cate_nombre?:      string;
        cate_descripcion?: string;
        id?:               number; 
    }
    produc_sku?:         string;
    produc_nombre?:      string;
    produc_precio?:      number;
    produc_descripcion?: string;
    produc_stock?:       number;
}

